prefooter_title: Planification
prefooter_items:
  -
    id: m0jw6lkz
    text: Adresse
    button:
      button_text: "1004-6455 rue Jean-Talon E<br>Saint-Léonard QC\_ H1S 3E8"
      button_link: 'https://www.google.com/maps/@49.7765574,4.6350001,3a,75y,56.55h,90t/data=!3m7!1e1!3m5!1slieJ1fXVjssRmIsmEAAaqg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D0%26panoid%3DlieJ1fXVjssRmIsmEAAaqg%26yaw%3D56.5522056816109!7i16384!8i8192?coh=205410&entry=ttu&g_ep=EgoyMDI0MDgyMS4wIKXMDSoASAFQAw%3D%3D'
  -
    id: m0jw7b03
    text: Téléphone
    button:
      button_text: '514 254-4111'
      button_link: 'tel:514 254-4111'
  -
    id: m0jw7ltv
    text: 'Sans frais'
    button:
      button_text: '1 888 254-4111'
      button_link: 'tel:1 888 254-4111'
  -
    id: m0jw7xfe
    text: Télécopieur
    button:
      button_text: '514 254-6537'
      button_link: 'tel:514 254-6537'
  -
    id: m0jw89xp
    text: Courriel
    button:
      button_text: info@planificationlica.ca
      button_link: 'mailto:info@planificationlica.ca'
  -
    id: m0jw8jw0
    text: Suivez-nous
    button:
      button_text: LinkedIn
      button_link: 'https://www.linkedin.com/company/planification-lica/?originalSubdomain=ca'
copyright_since: 2024
privacy_statement_type: none
